<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="BkList.aspx.cs" Inherits="LibMgmtSysApi.BkList" MasterPageFile="~/BIM.Master"%>

<%--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>List of Books</title>
</head>
<body>
    <form id="frmBkLst" runat="server">
    <div align="center">--%>
    <asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
         <br />
        <br />
        <br />
         
        <div style="background:	#FFE4B5; background-position:center;width:auto;height:100%;">
       <br />
      
        <asp:Label ID="Label1" runat="server" style="text-align: center" 
            Text="List of Books" Font-Bold="True" Font-Names="Bodoni MT" Font-Size="28px" 
            Font-Underline="True" ForeColor="#0033CC"></asp:Label>
            <div style="width: 1323px;height:350px;overflow:auto; margin-left:auto;margin-right:auto ;">
        <asp:GridView ID="gdvBkLst" runat="server" CellPadding="4" 
            EnableSortingAndPagingCallbacks="True" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            onrowediting="gdvBkLst_RowEditing" 
    style="position: relative; top: 4px; left: 3px; width: 1303px; height: 348px;" 
            DataKeyNames="ISBN" onrowcancelingedit="gdvBkLst_RowCancelingEdit" 
            onrowdeleting="gdvBkLst_RowDeleting" AutoGenerateColumns="False" 
            onrowupdating="gdvBkLst_RowUpdating" BackColor="White" BorderColor="#CC9966" 
                    BorderStyle="None" BorderWidth="1px">
            <RowStyle BackColor="White" ForeColor="#330099" />
            <Columns>
                <asp:BoundField  DataField="Title" HeaderText="Title" SortExpression="Title"  />
                <asp:BoundField  DataField="Author" HeaderText="Author" 
                    SortExpression="Author" />
                <asp:BoundField DataField="ISBN" HeaderText="ISBN" InsertVisible="False" 
                    ReadOnly="True" SortExpression="ISBN" />
                <asp:BoundField  DataField="Publisher" HeaderText="Publisher" 
                    SortExpression="Publisher" />
                <asp:BoundField  DataField="Year" HeaderText="Year" SortExpression="Year" />
            </Columns>
            <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
            <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
            <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" 
                />
            <EditRowStyle BorderStyle="Solid" />
        </asp:GridView>
        </div>
      <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
         </div>
    </asp:Content>
    <%--</div>
    </form>
</body>
</html>--%>